### ISSUE TITLE
show error when add android:fitsSystemWindows="true" 

### ISSUE THREAD

**Issue by gaoxuefeng** [androidx/constraintlayout#10]
`<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clipToPadding="false"
    tools:ignore="MergeRootFrame">

    <ImageView
        android:id="@+id/iv_activity_bg"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="centerCrop"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        tools:background="@android:color/holo_green_dark" />

    <FrameLayout
        android:id="@+id/fl_temp"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true"
        app:layout_constraintTop_toTopOf="parent">

        <include
            android:id="@+id/title_bar"
            layout="@layout/title_bar_style1" />
    </FrameLayout>

    <LinearLayout
        android:id="@+id/loading_empty_view"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/fl_temp">
  </LinearLayout>
</androidx.constraintlayout.widget.ConstraintLayout>`
it work error ,loading_empty_view Not enough space has been reserved for fl_temp when add  android:fitsSystemWindows="true"

**Comment by camaelon** [comment]
Hi, could you attache the title_bar_style1 layout ? thanks!

**Comment by rockyoung** [comment]
I have the same problem, all layout files that using ConstraintLayout as root element with the android:fitsSystemWindows="true" setting are all perform some strange error since update version from 2.0.1 to 2.0.2

**Comment by camaelon** [comment]
Hi, can you try if 2.0.3 fixes the issue? there was an update problem which manifested with window insets.

**Comment by rockyoung** [comment]
> Hi, can you try if 2.0.3 fixes the issue? there was an update problem which manifested with window insets.

2.0.3 is good!
