### ISSUE TITLE
WRAP_CONTENT behavior as minimum along a dimension

### ISSUE THREAD

**Issue by nullptr2this** [androidx/constraintlayout#120]
Unless I'm missing something, it's difficult or impossible to have a constraint layout child view match constraints but use its own content size as a minimum for a given dimension.  I think this concept is missing in view groups in general, but it seems most applicable in constraint layout.  

We appear to have the ability to request the opposite, that a view wrap content but also honor constraints if the constraints would prevent the view from increasing it's dimension to wrap the content (squeezing it if there isn't room) using layout_<dimension>="wrap_content" coupled with layout_constrained<dimension>="true|false", but the opposite could come in handy as well.  Allow the view to expand to match its parent, but to request not to compress less than its measured content.

**Comment by jafu888** [comment]
android:layout_width="0dp" 
app:layout_constraintWidth_min="wrap"
This does not work for you?

**Comment by nullptr2this** [comment]
The docs suggest that this is a dp based value, so I hadn't actually tried that.
