### ISSUE TITLE
[Bug / Question] Duration of global transition

### ISSUE THREAD

**Issue by mlykotom** [androidx/constraintlayout#124]
ConstraintLayout 2.0.4

I'm not sure whether I'm reporting a bug or it's desired behavior, but:

Preconditions:
- I'm in the middle of whatever transition
- I want to run "global" transition via `transitionToState()` (transition which doesn't have `constraintSetStart` set, but has only `End`) 

The duration of the global transition is not applied and duration of currently running transition is applied instead.
I guess the reason for that is, that duration is first taken from scene and then transition is applied

See [MotionLayout lines 2095-2097](https://github.com/androidx/constraintlayout/blob/main/constraintlayout/constraintlayout/src/main/java/androidx/constraintlayout/motion/widget/MotionLayout.java#L2095-L2097)

method `public void transitionToState(int id, int screenWidth, int screenHeight)`
![image](https://user-images.githubusercontent.com/3973717/106011295-9ed6e880-60ba-11eb-9b50-4da66c206cd2.png)

I guess the same would happen with regular transition - which has start+end constraints
I'm not sure whether there's some reason why it's this way or if it's a bug 🤷🏻‍♂️ 

Thanks!

**Comment by jafu888** [comment]
That was intentional because we wanted to related the velocity to the velocity of the previous  transition.
But I understand your need and I will look into it.

**Comment by jafu888** [comment]
We now have added an API which is
 transitionToState(id, duration);
if duration is -1 it is the current behavior.
duration of 0 is the behavior you wanted. (Use the duration specified in <Transition end=id. or default duration)
duration of > 0 is uses the time.
