### ISSUE TITLE
ConstraintLayout v2.0.2 seems to have rendering bugs

### ISSUE THREAD

**Issue by NahroTo** [androidx/constraintlayout#14]
There is an inconsistent bug in ConstraintLayout 2.0.2 that sometimes completely misrenders UI elements.
The problem is described in the thread here: https://kotlinlang.slack.com/archives/C0B8M7BUY/p1602767125009100

Switching back to 1.1.3 fixed my issues.

**Comment by drakeet** [comment]
+1

**Comment by drakeet** [comment]
You can try to switch back to 2.0.1, which fixed my issues.

**Comment by drakeet** [comment]
After updating from 2.0.1 to 2.0.2, we encountered an out-of-bounds exception with the ViewGroup dispatchDraw:
(Android 10)
![image](https://user-images.githubusercontent.com/5214214/96402656-0ef6e800-1209-11eb-8ba5-375e8bf200f3.png)

**Comment by GuilhE** [comment]
I'm getting layout transitions miss rendered and miss formatted and some included views not drawn at all 🤔

**Comment by camaelon** [comment]
Hi -- can you try with 2.0.3 ? I found an issue with incorrect update that might fixes this (it mostly showed somehow when dealing with windows insets,  but seems like a potential broader issue). Thanks!

**Comment by GuilhE** [comment]
Unfortunately for me `ActivityOptionsCompat.makeSceneTransitionAnimation` still miss render the transition.

**Comment by NahroTo** [comment]
Tested on v2.0.3, can't reproduce the bug anymore. The bug seems to be fixed 😄. Closing this issue.

**Comment by drakeet** [comment]
link to #21
