### ISSUE TITLE
How do I get the source code for each version？

### ISSUE THREAD

**Issue by zongxiaomi** [androidx/constraintlayout#15]
For some reason, I am using a lower version，i can`t find the source code in [Google's Maven](https://maven.google.com/web/index.html).Can you help me? 
Thank you very much

**Comment by jafu888** [comment]
Sorry we do not have the source code in Maven. We are trying to get the future releases to be in Maven.
 We only have 2.0.x in Github and no betas & alphas.

Before that it is not very simple to reconstruct them but: 
1.1.1 & 1.1.2 can be found 
https://android.googlesource.com/platform/frameworks/opt/sherpa/+log/refs/tags/studio-4.0.0/constraintlayout
