### ISSUE TITLE
MotionLayout - Jump to state

### ISSUE THREAD

**Issue by Uiasdnmb** [androidx/constraintlayout#184]
Am I missing something or is there no direct way to jump to specific state without animation that doesn't involve manipulating progress?

I tried using `setState` which seems to do nothing or `transitionToState(state, duration)` but neither of those seem to work properly for this case (`0` duration is just a hint instead of skipping animation which is rather misleading in my opinion).

I find the process quite confusing for something that should be a basic operation especially when there are multiple transitions. I'm currently using a workaround by extending `MotionLayout`:

```
class MotionLayoutWithJump : MotionLayout {
    // (... constructors etc)

    private var pendingJump = -1

    fun jumpToState(state: Int) {
            if(!isAttachedToWindow) {
                pendingJump = state
                return
            }
            val target = when (state) {
                startState -> 0f
                endState -> 1.0f
                else -> {
                    // need to alter current transition to perform progress jump
                    val t = definedTransitions.find {
                        it.startConstraintSetId == state || it.endConstraintSetId == state
                    } ?: throw IllegalArgumentException("Provided state is not defined for any transition")
                    setTransition(t)
                    if (state == t.endConstraintSetId) 1.0f else 0f
                }
            }
            super.setProgress(target)
            updateState(state, getConstraintSet(state))
            pendingJump = -1
    }

    override fun onAttachedToWindow() {
        super.onAttachedToWindow()
        if(pendingJump != -1){
            jumpToState(pendingJump)
        }
    }
}
```
It's not perfect of course because it will conflict with any animated transitions that are called while view is detached and I have not tested how it behaves with nested scrolling either.

So the request is self explanatory: can we get a native jump to state method that will skip all animations?

**Comment by jafu888** [comment]
Thanks. We have a change with (jumpToState) something like this in the next Beta
