### ISSUE TITLE
The last letter is cut off in motionlayout

### ISSUE THREAD

**Issue by xuyisheng** [androidx/constraintlayout#196]
with the demo of https://developer.android.com/training/constraint-layout/motionlayout/examples#coordinatorlayout_12
it shows different display styles.

in 2.1.0-beta01, it shows like that:
![image](https://user-images.githubusercontent.com/7419202/112604593-4a997c00-8e51-11eb-8243-174dd347d6a5.png)

in 2.0.1:
![image](https://user-images.githubusercontent.com/7419202/112604712-6e5cc200-8e51-11eb-91a2-b547689e4d34.png)

it's very strange that the last letter was dropped.

**Comment by xuyisheng** [comment]
any progress？

**Comment by kroegerama** [comment]
Maybe related to #232?

**Comment by xuyisheng** [comment]
2.1 fixed
