### ISSUE TITLE
[BUG] ConstraintLayout bug with Swipe gesture on offscreen view

### ISSUE THREAD

**Issue by recoverrelax** [androidx/constraintlayout#20]
issuetracker: https://issuetracker.google.com/issues/172187076
Any workaround I can apply? Thanks in advance

**Comment by jafu888** [comment]
Have you tried with 2.1-alpha2?

**Comment by recoverrelax** [comment]
yes. Instead of a bugged animation. It doesn't work at all. Nothing animates. This is really easy to reproduce as stated in the issuetracker, and happens 100% of the time in small screens, which completely renders MotionLayout useless on these screens. If you need any help to identify the issue please don't hesitate to ask. I'll gladly help since i want this bug fixed so much :p

**Comment by recoverrelax** [comment]
This is what happens. The video will show two scenarios. First, the scenario where the screen has enough height so that the recyclerView is initially visible (no problems here). The second, I resize the preview screen and the animation stops working. That is the bug. I have a workaround if you need any more intel about this bug.
https://user-images.githubusercontent.com/4225799/108198009-fe04a780-7112-11eb-91b4-e5e0228d36a2.mov
