### ISSUE TITLE
ConstraintLayout v2.0.2 & v2.0.4 may cause crash when dispatchDraw

### ISSUE THREAD

**Issue by drakeet** [androidx/constraintlayout#21]
After updating from 2.0.1 to 2.0.2 & **2.0.4**, we encountered an out-of-bounds exception with the ViewGroup `dispatchDraw`:
(Android 10)
![image](https://user-images.githubusercontent.com/5214214/96402656-0ef6e800-1209-11eb-8ba5-375e8bf200f3.png)

This problem still occurs in 2.0.4. Downgrading to 2.0.1 solved the problem again.

**Comment by camaelon** [comment]
Wouldn't that be a crash in ViewPager.getChildDrawOrder() though?

**Comment by drakeet** [comment]
Yes, but it seems that the new ConstraintLayout version triggered the ViewPager exception.

**Comment by camaelon** [comment]
Could you share a repro project? Thanks

**Comment by drakeet** [comment]
@camaelon I can't reproduce it, but my user told me that he can reproduce this problem stably. It is a Huawei device. So I opened this issue to see if anyone has the same problem as us. It doesn't seem to be there. I will close this first and wait until I am sure that it can reproduce and find the reason.
