### ISSUE TITLE
Motion scene not triggering with NestedScrollView as anchor point in beta02

### ISSUE THREAD

**Issue by gusandrianos** [androidx/constraintlayout#221]
Hi there!

I have a scenario which works fine on 2.1-beta01 and before but breaks on beta02. 

I have the following transition 

```
     <Transition
        android:id="@+id/transition"
        app:constraintSetEnd="@id/collapsed"
        app:constraintSetStart="@id/expanded"
        app:duration="1000"
        app:motionInterpolator="easeInOut">
        <OnSwipe
            app:dragDirection="dragUp"
            app:moveWhenScrollAtTop="true"
            app:touchAnchorId="@id/nsv_container"
            app:touchAnchorSide="top" />
    </Transition>
```

The layout I'm using has a `MotionLayout` as the parent and a child `NestedScrollView` which contains a `LinearLayout` with some chid views. 
Before beta02, the Motion animation would trigger as soon as I started scrolling the contents of the `NestedScrollView` but on beta02, I have to reach the bottom of the `NestedScrollView` to trigger it.

The layout is company code so I can't share it but I think I've given enough context as to what's happening. 

Edit: More context, the MotionLayout is used to create a "Collapsing Toolbar" style animation, nothing too complex.

**Comment by finneapps** [comment]
I am having the same issue with NestedScrollView + MotionLayout

**Comment by jafu888** [comment]
This will be fixed in next build.

**Comment by 0829752747** [comment]
[Uploading งานนำเสนอไม่มีชื่อ.pdf…]()

**Comment by 0829752747** [comment]
แก้ไขด้วย

**Comment by gusandrianos** [comment]
As of `2.1.0-rc1`, this is working fine!
