### ISSUE TITLE
Test suite and changelog 

### ISSUE THREAD

**Issue by jeduden** [androidx/constraintlayout#25]
I am trying to find a problem with a layout that works on 2.0.1 but doesn't work anymore on 2.0.2, 2.0.3 and 2.0.4.

In order to zoom in on the problem, i was trying to find a change log, but couldn't find it. 

Further, I was wondering if there is a test suite that is being executed before new versions are released, since i was wondering if a test case similar to my layout exists, that could point me in a direction how to fix the layout.

**Comment by kaeawc** [comment]
There is now documentation about how to run the project and all of its tests, as well as CI to show if the current build is passing.

Some of the tests aren't yet automated in Github Actions, but they are now documented on how to run them locally.

There isn't really a change log beyond what you're seeing in the [Wiki](https://github.com/androidx/constraintlayout/wiki) and the [ConstraintLayout release notes on AndroidX](https://developer.android.com/jetpack/androidx/releases/constraintlayout).

**Comment by jeduden** [comment]
Thanks ! I was looking for these pointers !

**Comment by kaeawc** [comment]
@camaelon looks like we can close this
