### ISSUE TITLE
Suppprt lazy add xml attribute

### ISSUE THREAD

**Issue by EaseTheWorld** [androidx/constraintlayout#257]
ViewStub is useful but inconvenient.
- It required a separate xml which is not good for manage and read.
- id and inflatedId needs to be same if you use ViewBinding.

So I suggest a new attribute which indicates a lazy add. app:layout_constraintLazy="true".

It is different from ViewStub because it is inflated 
and where to added is set, except it is not in view tree.

If you want to add the view, call  ConstrainLayout.addView(lazyViewId) (or maybe new method needed.)

I'm not sure this attribute makes sense. maybe virtual helper(like Guideline, Barrier) style is more suitable.

But this lazy add will lighten your viewtree which is the goal of ConstraintLayout.

**Comment by jafu888** [comment]
If it is inflated and location is set. 
What is the difference from visibility="gone"?
The "heavy" part is inflation.
If it was not part of the tree. It is inaccessible and should be garbage collected.

**Comment by EaseTheWorld** [comment]
You are right. I misunderstood.
I thought whether attached or not can make difference.
I'll close the issue.
