### ISSUE TITLE
CustomAttribute does't work when used in KeyAttribute

### ISSUE THREAD

**Issue by Ariorick** [androidx/constraintlayout#319]
CustomReference does't work when used in KeyAttribute. Same CustomAttribute works fine if you put in Constraint
```
            <KeyAttribute
                motion:framePosition="50"
                motion:motionTarget="@+id/imageView">
                <CustomAttribute
                    motion:attributeName="imageResource"
                    motion:customReference="@drawable/icon_back"/>
            </KeyAttribute>
```
or
```
            <KeyAttribute
                motion:framePosition="50"
                motion:motionTarget="@+id/imageView">
                <CustomAttribute
                    motion:attributeName="colorFilter"
                    motion:customReference="@color/black"/>
            </KeyAttribute>
```
I'm using constraintLayout 2.1.0-beta02

**Comment by jafu888** [comment]
This is working as intended 

KeyAttribute are for continuous variables (floats, integers or colors). 
I.e. CustomFloat,CustomColor,CustomDimension etc.
For a custom value to work it must be given the value in the start and end ConstraintSets.


KeyTriggers can be use to implement triggering a call at crossing which can be any type of CustomAttribute
