### ISSUE TITLE
Equal width and equal height constraint

### ISSUE THREAD

**Issue by himamis** [androidx/constraintlayout#366]
It would be nice to have a constraint that sets the view height to be equal to another views height (or width).

Use case: I have a view A that has a complicated set of constraints (involving barriers) that define it's height. I have another view B, that is invisible because it's out of screen, something like a detail view. To show this view, I want to animate it into place from the bottom. I want the animation to look like the view B just "translates" into place, and not "grows" there. For this, I would need a constraint that specifies that view B has the same height as view A.

**Comment by jafu888** [comment]
This feature is more difficult than it would seam to implement because it generates a cascade of edge cases.

In MotionLayout you can achieve the affect you are looking for by using a 
```xml
<KeyFrame>
  <KeyPosition 
    motion:target="..." 
    motion:framePosition="1", 
    motion:percentHeight="100" />
 </KeyFrame>
```
This would set the high of the incoming view to its final high at the very start of the transition.

**Comment by himamis** [comment]
Thank you, that is good workaround.
