### ISSUE TITLE
Access XML Scene

### ISSUE THREAD

**Issue by himamis** [androidx/constraintlayout#370]
In our project there are transitions between every constraint set. Defining these manually, in the xml is very tedious. I would like to be able to define them programmatically. But current, to define a transition, we need access to a MotionScene, which is only accessible if it was created programmatically.

Feature request:
Add a getter in the MotionLayout class to the MotionScene object, so that it's accessbile, even if it is created from the xml file.

**Comment by jafu888** [comment]
There are lots of potential  issues with direct access. 
Depending on the current stat of the MotionLayout.
I will add a warning in the javadoc later.
