### ISSUE TITLE
Programmatic view creation and VISIBILITY_MODE_IGNORE

### ISSUE THREAD

**Issue by CeH9** [androidx/constraintlayout#38]
I'm creating views programmatically in **onCreate** and add them to **CostraintLayout**, also i set **ConstraintSet.VISIBILITY_MODE_IGNORE**, cuz some of newly created views should be gone/invisible, but

```
constraintSet.applyTo(..)
```
applies in next frame, so visibility changes from onCreate has no effect and all views is **VIEW.VISIBLE**

Currently i'm using following dirty hack:

``` kotlin
    private fun gone(view: View, constraintSet: ConstraintSet) {
        if (isFirstRender) {
            constraintSet.setVisibility(view.id, View.GONE)
        } else {
            view.visibility = View.GONE
        }
    }
```

Is it bug? Can i achieve more elegant solution?

**Comment by jafu888** [comment]
I need a little more details:
I am not sure ConstraintSet.VISIBILITY_MODE_IGNORE is relevant to ConstraintLayout
What are you hoping to achieve by setting it?
Why are you maintaining the ConstraintSet?
Why 
```
 if (isFirstRender) {
            constraintSet.setVisibility(view.id, View.GONE)
        } else {
            view.visibility = View.GONE
        }
```
Not 
```
            constraintSet.setVisibility(view.id, View.GONE)
            view.visibility = View.GONE
```
?

**Comment by CeH9** [comment]
Yep, i didin't mention that i setting up relations between generated views. e.g. 
``` kotlin
constraintSet.connect(labelId, ConstraintSet.START, inputId, ConstraintSet.START)
```
Overall overview:
There is a virtualFlow with couple inputs in a chain, each of input has "connected" label and error TextViews. 
UI is driven by state: LiveData + monolith state of whole screen which renders on every change. Current View Framework doesn't friendly for such approach so there is a lot of optimisations inside my observe function aka "render state". For example, i can "calculate diff" between old and new states and update only small part of my view tree, e.g. one input + connected label and error.
So render state will looks like:
``` kotlin
val itemToUpdate = magicDiffAlrgorithm(state)
if (itemToUpdate.isVisible) {
   view.visibility = View.VISIBLE
} else {
   view.visibility = View.GONE
}
...
view.text = itemToUpdate.title
// and so on
```

 In this case **view.visibility = View.GONE** will works fast, while **constraintSet.setVisibility(view.id, View.GONE)** breaks this idea due to nature of **constraintSet.applyTo(..)**. I can't use it for frequent changes cuz it leads to performance issues. 

P.S. issue partially solved by checks on false-positive updates e.g. 
``` kotlin
fun View.show(): View {
    if (visibility == View.VISIBLE) return
    visibility = View.VISIBLE
} // or similar via ConstraintSet.getVisibility(int viewId)
```
But it doesn't helps if you realy need to change visibility frequintly. The worst part is that i forced to use both approaches: ConstraintSet for first frame draw and eficient for rest ones.MVI 

P.S. i chose such architecture with manual diffing to more seamless migration to compose wihtout diving in heavy frameworks like MVICore or Litho

![image](https://user-images.githubusercontent.com/7687412/100154686-a6a5c100-2eae-11eb-8b9e-1a936d32de30.png)

**Comment by jafu888** [comment]
ConstraintSets are not designed for frame by frame apply. 
ConstraintLayout is a linear equation solver. It will be slow if you update every frame managing 28 widgets. 
If you are changing visibility frequently (especially to Gone). 
Reactive frameworks like compose work by doing a diff on your update. 
ConstraintSet it not built that way. (And to some extent ConstraintLayout could be slow to) 
You could reduce your change by using ConstraintProperties which are per view.
