### ISSUE TITLE
addView() seems to break MotionLayout

### ISSUE THREAD

**Issue by remvst** [androidx/constraintlayout#386]
Using version `2.0.4` and `2.1.0` (haven't noticed any difference regarding my specific issue)

I'm currently building a screen that features a module that the user can drag from the bottom. Behind the module is the main content of the screen, which is highly dynamic and could receive an `addView()`/`removeAllViews()` at any time.
`addView()` is NOT done on a direct child of my motion layout. It is done several layers below.

I'm noticing that when any `addView()`/`removeAllViews()` happens, if the motion layout is in the middle of a transition, the container gets laid out fine, however all the children are now laid out with x = 0, y = 0, width = 0, height = 0, measuredWidth = 0, measuredHeight = 0. I have tried hardcoding the layout parameters of the children with no luck.

The motion layout looks like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.motion.widget.MotionLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/motion_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:layoutDescription="@xml/scene_expandable_module"
    tools:showPaths="true">

    <androidx.constraintlayout.widget.Guideline
        android:id="@+id/half_screen_guideline"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:orientation="vertical"
        app:layout_constraintGuide_percent="0.5" />

    <FrameLayout
        android:id="@+id/main_content"
        android:layout_width="@dimen/zero_spacing"
        android:layout_height="@dimen/zero_spacing" />

    <FrameLayout
        android:id="@+id/bottom_sheet"
        android:layout_width="@dimen/zero_spacing"
        android:layout_height="@dimen/zero_spacing" />

    <View
        android:id="@+id/draggable_top"
        android:layout_width="@dimen/zero_spacing"
        android:layout_height="@dimen/zero_spacing" />

</androidx.constraintlayout.motion.widget.MotionLayout>
```

And the motion scene looks like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<MotionScene xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <Transition
        app:constraintSetEnd="@id/end"
        app:constraintSetStart="@id/start"
        app:duration="300">
        <OnSwipe
            app:maxAcceleration="15"
            app:touchAnchorId="@id/draggable_top" />
    </Transition>

    <ConstraintSet android:id="@+id/start">
        <Constraint
            android:id="@id/draggable_top"
            android:layout_width="@dimen/zero_spacing"
            android:layout_height="@dimen/zero_spacing"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent" />

        <Constraint
            android:id="@id/main_content"
            android:layout_width="@dimen/zero_spacing"
            android:layout_height="@dimen/zero_spacing"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <Constraint
            android:id="@id/bottom_sheet"
            android:layout_width="@dimen/zero_spacing"
            android:layout_height="@dimen/zero_spacing"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/draggable_top" />
    </ConstraintSet>

    <ConstraintSet android:id="@+id/end">
        <Constraint
            android:id="@id/draggable_top"
            android:layout_width="@dimen/zero_spacing"
            android:layout_height="@dimen/zero_spacing"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <Constraint
            android:id="@id/main_content"
            android:layout_width="@dimen/zero_spacing"
            android:layout_height="@dimen/zero_spacing"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <Constraint
            android:id="@id/bottom_sheet"
            android:layout_width="@dimen/zero_spacing"
            android:layout_height="@dimen/zero_spacing"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/draggable_top" />
    </ConstraintSet>

</MotionScene>
```

`main_content` is the parent of the view that will get the dynamic children, while `bottom_sheet` is the module that I want to let the user drag up and down.
`main_content` is not meant to be resized at all. I always want it to take all the available room on the screen.

Everything **seems** to work fine if I add/remove views outside of the transition, however if the user is in the middle of dragging the module up or down, all the dynamic views get that width/height of zero.

Am I doing something wrong? I've been digging at this issue for the past couple of days and can't figure out why those views can't be laid out properly. I've also tried calling `forceLayout()`, `requestLayout()`, `invalidate()` on the container, with no luck,

**Comment by jafu888** [comment]
Try adding 
```xml
    <Transition    
    ...
     motion:layoutDuringTransition="honorRequest" 
     \>
```

**Comment by remvst** [comment]
> Try adding
> 
> ```
>     <Transition    
>     ...
>      motion:layoutDuringTransition="honorRequest" 
>      \>
> ```

Thanks for the reply. I have tried it and while it looks very promising, I am still seeing cases where the views' layouts are completely stuck in that 0x0 state.

Updating the views in that child looks like this:
```kotlin
        removeAllViews()

        // items: List<T>
        // itemToView: (T) -> View
        for (item in items) {
            val view = itemToView(item)
            addView(view)
        }
```

The bug seems to happen when I do the drag gesture up and down a lot, causing many visibility changes of the child containing all these dynamic views. The code looks like this:
```kotlin
 private fun onModuleStateChange() {
    container.isInvisible = motionLayout.progress > 0.8f
}
```

I've tried resetting the layout params in `onTransitionChange` with no luck. Resetting them in `onTransitionCompleted` seems to work but it's not ideal as there is an inbetween state where the views aren't visible.

**Comment by jafu888** [comment]
I am still confused as to all that is happening in you code but I can  give a few relevant bits of information 

- MotionLayout does not use layout parameters. It uses the MotionScene and its constraintSets 
- MotionLayout only controls its direct children
- All views in MotionLayout need id for the control to work. 
- Modify ConstraintSets used in MotionLayout (Search Stack Overfflow etc.  for examples)

Generally it is not a good idea to mix animation approaches so if you want a view to be invisible in MotionLayout
Added it to the MotionScene or Modify the ConstraintSets dynamically   
You can look at the code in the MotionHelper MotionEffect as an example of dynamic inserting of complex motion behavior.
