### ISSUE TITLE
Setting progress with a velocity always transitions to end

### ISSUE THREAD

**Issue by Kurounin** [androidx/constraintlayout#435]
When setting progress with a velocity:
```
motionLayout.setProgress(06f, 200f);
```
the scene transitions to end, because of this:
https://github.com/androidx/constraintlayout/blob/d782fcb844a1bb38130bba3390ddd972a40ddba6/constraintlayout/constraintlayout/src/main/java/androidx/constraintlayout/motion/widget/MotionLayout.java#L1593
Shouldn't that code be:
```
animate(pos);
```

Or how can we animate to a specific progress?

**Comment by jafu888** [comment]
It is not specifically supported.  (For fear of abuse) 
setProgress(pos)  means jump to pos and stop.
setProgress(pos, vel)  means jump to pos and move at this velocity.

The most natural way is achieve the affect you are looking for is ObjectAnimator

There is a method used by the touch handlers. touchAnimateTo(int touchUpMode, float position, float currentVelocity)
But it is not designed for the needs of Application writers.

**Comment by Kurounin** [comment]
@jafu888 Thanks for the explanation.
