### ISSUE TITLE
setProgress(position, velocity) always sets position to 1

### ISSUE THREAD

**Issue by PaulKlauser** [androidx/constraintlayout#437]
# Issue
Calling `setProgress(position: Float, velocity: Float)` always results in the layout's progress being set to 1. Looks like this is caused by always calling `setPosition(1f)` here: https://github.com/androidx/constraintlayout/blob/df23aa827b2f5922dea580f042cc0f652c33bd0c/constraintlayout/constraintlayout/src/main/java/androidx/constraintlayout/motion/widget/MotionLayout.java#L1593

It's not clear to me why that would be called with a value of 1f every time. If a PR removing that line would be helpful, I'm happy to do it, but it's not clear to me why that was added in the first place, the git history seems to be lost from the migration to GitHub.

## Workaround
My workaround for now is to override that method locally and just call the `setProgress(position: Float)` overload instead, as that doesn't exhibit this behavior. Granted velocity is now being lost on that call.

## Examples
[MotionLayoutProgress.zip](https://github.com/androidx/constraintlayout/files/7509130/MotionLayoutProgress.zip)

https://user-images.githubusercontent.com/6461398/141033189-557b6d7b-c9cc-447e-b422-ce5654a68c0c.mp4

**Comment by PaulKlauser** [comment]
This issue is also the cause of the behavior described in: https://issuetracker.google.com/issues/199754674

**Comment by jafu888** [comment]
It is a bug.
The use case of calling this API velocity  was assumed to be > 0.
it will probably be changed to if (v!=0.0f) anaimateTo(0>1?1:0);

**Comment by PaulKlauser** [comment]
This appears to be fixed by @jafu888 's commit mentioned above, which is released in v2.1.2. Closing.
