### ISSUE TITLE
When set setBaselineDistance() after connet(), layout result not correct.

### ISSUE THREAD

**Issue by xtuzy** [androidx/constraintlayout#443]
Hello, i'm creating constraintlayout for WPF, i want create constraint rely on baseline for some text control, the step of creating constraint  is:
1. user load ConstraintWidget.connect() to define constraint
2. wpf auto measure some text control, calculate baseline position and setBaselineDistance() in WPF measure cycle
3. load ConstraintWidgetContainer.layout() to calculate control position in WPF measure cycle

but the result not correct.

I open this java project find test about baseline, in constraintlayout\core\src\test\java\androidx\constraintlayout\core\OptimizationsTest.java, i move setBaselineDistance() after connet(), the test failed.
```
@Test
    public void testBasicBaseline() {
        ConstraintWidgetContainer root = new ConstraintWidgetContainer(0, 0, 600, 600);
        ConstraintWidget A = new ConstraintWidget(100, 20);
        ConstraintWidget B = new ConstraintWidget(100, 20);
        root.setDebugName("root");
        A.setDebugName("A");
        B.setDebugName("B");
        //A.setBaselineDistance(8);
        //B.setBaselineDistance(8);
        root.add(A);
        root.add(B);
        A.connect(ConstraintAnchor.Type.TOP, root, ConstraintAnchor.Type.TOP);
        A.connect(ConstraintAnchor.Type.BOTTOM, root, ConstraintAnchor.Type.BOTTOM);
        A.connect(ConstraintAnchor.Type.LEFT, root, ConstraintAnchor.Type.LEFT);
        B.connect(ConstraintAnchor.Type.LEFT, A, ConstraintAnchor.Type.RIGHT);
        B.connect(ConstraintAnchor.Type.BASELINE, A, ConstraintAnchor.Type.BASELINE);
        
        A.setBaselineDistance(8);
        B.setBaselineDistance(8);
        
        Metrics metrics = new Metrics();
        root.fillMetrics(metrics);
        root.setOptimizationLevel(Optimizer.OPTIMIZATION_STANDARD);
        root.layout();
        System.out.println("1) root: " + root + " A: " + A + " B: " + B);
        System.out.println(metrics);
        assertEquals(A.getTop(), 290);
        assertEquals(B.getTop(), A.getTop());
    }
```
Is it necessary to setBaselineDistance before connect ？I don't know it ‘s bug or feature. Is there any way to change？

**Comment by jafu888** [comment]
I asked @camaelon hopefully he has time.

  but I suspect it just needs to be non 0 before the connect.
i.e.  you can have
 A.setBaselineDistance(1);
 B.setBaselineDistance(1); 
 before the connect 
 Than after set it to what ever comes from the WPF engine. 
 (Same thing applies if you change the size of the font)
Just to say that those widgets have baselines.

**Comment by camaelon** [comment]
Yeah that's a bug -- setBaselineDistance() should set the margin on the baseline anchor if it's set. IIRC setBaselineDistance is only used by the direct solver though, in the android xml case we simply pass the baseline margin to connect()

**Comment by camaelon** [comment]
So basically -- seems to be working as intended, and you shouldn't use that method and instead set the baseline margin in connect().

**Comment by xtuzy** [comment]
> I asked @camaelon hopefully he has time.
> 
> but I suspect it just needs to be non 0 before the connect. i.e. you can have A.setBaselineDistance(1); B.setBaselineDistance(1); before the connect Than after set it to what ever comes from the WPF engine. (Same thing applies if you change the size of the font) Just to say that those widgets have baselines.

@jafu888  This can let test passed,thank you! I like this tips.
>Just to say that those widgets have baselines.

**Comment by xtuzy** [comment]
@camaelon
Sorry, i don't know what you mean.
I found set baseline way is:
First i need set setBaselineDistance(1) before connect(),like @jafu888 say
>Just to say that those widgets have baselines.

Then set  measure.measuredBaseline in [ConstraintLayout.innerMeasure](https://github.com/androidx/constraintlayout/blob/7c2cfc4c3d54765308f88c6ea19a3368a1e2573f/constraintlayout/swing/src/main/java/org/constraintlayout/swing/ConstraintLayout.java#L185) .
What you mean is just set widgetA.connect(BASELINE,widgetA,TOP, margin) ? But measure.measuredBaseline in ConstraintLayout.innerMeasure must set, i found it will let widget.BaselineDistance aways be 0 if i don't set.
