### ISSUE TITLE
constraintlayout-compose API reference is not accessible on d.android.com

### ISSUE THREAD

**Issue by LouisCAD** [androidx/constraintlayout#468]
Hello!

I'm quite excited to use ConstraintLayout in Compose!
That said, I'm unable to find the API reference (aka. KDoc) for it.

CoordinatorLayout has both KDoc and Javadoc here: https://developer.android.com/reference/kotlin/androidx/coordinatorlayout/widget/package-summary

And the View system ConstraintLayout has Javadoc (no KDoc) here: https://developer.android.com/reference/androidx/constraintlayout/widget/package-summary

But this doesn't includes the compose specific APIs.

Could you please ensure that we can easily access the API reference for these APIs?

Thank you and have a great day!

Louis CAD

**Comment by oscar-ad** [comment]
The reference for ConstraintLayout in Compose is now available... for now on a separate page.

You can find it in the Android reference page https://developer.android.com/reference

ie: https://developer.android.com/reference/kotlin/androidx/constraintlayout/compose/package-summary
