### ISSUE TITLE
Changes in ConstraintSet are not rendered correctly.

### ISSUE THREAD

**Issue by magillus** [androidx/constraintlayout#473]
I found issue when trying to change the constraint set after first one loaded.

I did use `remember mutableStateOf` to change the JSON5 constraint and create new `ConstrintSet` with the changes to feed into `ConstraintLayout`

Observed in logs is that the "Constraints: ...." log line shows the new Value to be set and renders the change (visible on video as blink) and again the "Constraints:..." log line shows up with old value. 

When tried to debug this there were 2 invalidations of ConstraintLayout, first when when paused on breakpoint - showed fine rendered compose set.
Second pass did break the view and even left some views with not right constraints.

```

                        val constraints = remember { mutableStateOf(resConstraints) }
                        Log.i("MainActivity", "Constraints: ${constraints.value}")

                        Greeting("Android", ConstraintSet(constraints.value))
```

With Greeting function:
```

@Composable
fun Greeting(name: String, constSet: ConstraintSet) {
    ConstraintLayout(
        constSet,
        modifier = Modifier
            .width(300.dp)
    ) {
        Text(
            text = "Hello $name!",
            modifier = Modifier
                .wrapContentWidth()
                .layoutId("txt_hello", "")
        )
        Text(
            text = "Test value",
            modifier = Modifier
                .wrapContentWidth()
                .layoutId("txt_test", "")
        )
        Image(
            painter = painterResource(id = android.R.drawable.ic_delete), contentDescription = "",
            modifier = Modifier
                .layoutId("img_settings", "")
        )
    }
}
```

The layouts are in values at: https://github.com/magillus/ConstraintSetChangesTest/blob/main/app/src/main/java/com/example/changeconstraintsettest/Constants.kt

### Changes of the state can be visible in attached video

https://user-images.githubusercontent.com/729803/147782379-fb1ce993-cf05-41c7-8834-fd8fc3c59f74.mp4

Sample project: https://github.com/magillus/ConstraintSetChangesTest

**Comment by oscar-ad** [comment]
This is happening because the constraints are being assigned on the Button's content instead of onClick.

**Comment by magillus** [comment]
Thank you, I was blind not seeing this before.
