### ISSUE TITLE
[Compose] Vertical chain does not respect the horizontal guideline

### ISSUE THREAD

**Issue by MasoodFallahpoor** [androidx/constraintlayout#474]
I'm using constraintlayout-compose version 1.0.0-rc02

This is what I want to achieve: Suppose the height of the screen is divided into two equal halves. I want to vertically center two `Text` composables in the lower half.

This is the code I'm using:

```kotlin
    ConstraintLayout(modifier = Modifier.fillMaxSize()) {
        val (text1, text2) = createRefs()
        val guideline = createGuidelineFromTop(0.5f)
        createVerticalChain(text1, text2, chainStyle = ChainStyle.Packed)
        Text(
            modifier = Modifier.constrainAs(text1) {
                top.linkTo(guideline)
                bottom.linkTo(text2.top)
            },
            text = "Text1"
        )
        Text(
            modifier = Modifier.constrainAs(text2) {
                bottom.linkTo(parent.bottom)
                top.linkTo(text1.bottom)
            },
            text = "Text2"
        )
    }
```

The above code gives the following output which is wrong. Basically, the vertical chain is ignoring the fact that the top of the top `Text` composable is constrained to the guideline, not to the top of the parent.

![Screenshot_1640897702](https://user-images.githubusercontent.com/8100951/147787824-3d74cf8a-d1e5-4784-80a1-8a8694f1eef8.png)

Not sure but could be related to #392

**Comment by jafu888** [comment]
Unfortunately You tried created chains in two ways.
` createVerticalChain(text1, text2, chainStyle = ChainStyle.Packed)`
This created a vertical chain by default attached to the parent.
```            
      top.linkTo(guideline)
      bottom.linkTo(text2.top)
      
      bottom.linkTo(parent.bottom)
      top.linkTo(text1.bottom)
``` 
This created another chain.
Unfortunately the first one won.
So you can ether remove the first one. (but how do you define packed?)
or remove the second.
if  you would need to add some lines...
```
    val guideline = createGuidelineFromTop(0.5f)
    val chain = createVerticalChain(text1, text2, chainStyle = ChainStyle.Packed)
    constrain(chain) {
        top.linkTo(guideline)
    }
```

**Comment by MasoodFallahpoor** [comment]
The way I implemented the above layout in Compose is based on how I would implement it in the View System. Let's say I want to implement the same layout using XML. I use the following code:
```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <androidx.constraintlayout.widget.Guideline
        android:id="@+id/guideline"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        app:layout_constraintGuide_percent="0.5" />

    <TextView
        android:id="@+id/text1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Text1"
        app:layout_constraintBottom_toTopOf="@id/text2"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/guideline"
        app:layout_constraintVertical_chainStyle="packed" />

    <TextView
        android:id="@+id/text2"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Text2"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/text1" />

</androidx.constraintlayout.widget.ConstraintLayout>
```

The above XML layout produces the following output which is correct:

![Screenshot_1641033884](https://user-images.githubusercontent.com/8100951/147848875-bc34d7cd-b3df-4fb5-a9ef-968254de0a55.png)

Anyway, let's say I use the second solution you provided. I mean this:
```kotlin
    val guideline = createGuidelineFromTop(0.5f)
    val chain = createVerticalChain(text1, text2, chainStyle = ChainStyle.Packed)
    constrain(chain) {
        top.linkTo(guideline)
    }
```

The problem is that `createVerticalChain` returns `Unit`. This means that the following line gives an error because `constrain` requires an instance of `ConstrainedLayoutReference` whereas `chain` is `Unit`:

```kotlin
constrain(chain)
```

**Comment by jafu888** [comment]
Both have issues for you. No packed command in the traditional way.
The createVerticalChain is in the source code now (added Dec 15 ) but we have not done a release.
The only way to achieve this in the current release is in the JSON syntax. 
We will be working on a release in the next few weeks.

**Comment by oscar-ad** [comment]
Closing as this is supported in 1.0.0

Modifier:
```kotlin
   ConstraintLayout {
       val (tex1, text2) = createRefs()
       
       val vChain =  createVerticalChain(text1, text2)
       constrain(vChain) {
           top.linkTo()
           bottom.linkTo()
       }

       Text(modifier = Modifier.constrainAs(text1) {...}
       ...
   }
```

ConstraintSet:
```kotlin
   ConstraintSet {
       val text1 = createRefFor("text1")
       val text2 = createRefFor("text2")
       
       val vChain =  createVerticalChain(text1, text2)
       constrain(vChain) {
           top.linkTo()
           bottom.linkTo()
       }
       
       constraint(text1) {...}
       constraint(text2) {...}
       ...
   }
```
