### ISSUE TITLE
Running ConstraintLayout live inspector

### ISSUE THREAD

**Issue by adrianwitaszak** [androidx/constraintlayout#479]
Hi. How do i run ConstrainLayout Link desktop app?

"run your app and your phone or emulator and the live inspector app on your desktop"

got constrain layout project opened but how do i build this app

**Comment by jafu888** [comment]
That is a huge miss. 
You can down load and compile it. 

But it is a pure java application we should provide a "fat jar" 

Download [Link.jar](https://github.com/androidx/constraintlayout/raw/main/desktop/ConstraintLayoutInspector/Link.jar)
Run using "java -jar Link.jar"

**Comment by jafu888** [comment]
Let me know if you were able to run it.

**Comment by adrianwitaszak** [comment]
Thank you very much :) app works. Need to test it now if it works with my app

**Comment by adrianwitaszak** [comment]
All right. 
So i added LinkServer.kt to project.
call LinkServer in Applcation 
`override fun onCreate() {
        super.onCreate()
        Log.d("Application", "Application")
        LinkServer().start()
    }`
Forwarded ports 
`./adb forward tcp:9999 tcp:9999`
and launched app in emulator

and... ConstrainLayoutLink doesn't show anything, not connecting i mean

**Comment by jafu888** [comment]
Looks like you are close. 
Make sure you have in your json `  Header: { exportAs: 'xxxxxx'},`
And the Composable makes it to the screen at least once.

The link server will not expose it otherwise.

**Comment by adrianwitaszak** [comment]
I got it :) Forgot about Header :)
Got connected and json is showing, but nothing in layout inspector. i'll try it with sample code.
i'm in IntelliJ not in AS, if it matters

**Comment by jafu888** [comment]
Looks like we have a regression. 
Looking into it....

**Comment by jafu888** [comment]
I upload a fixed version / code

**Comment by adrianwitaszak** [comment]
i can see debug preview now :) 
on more issue, nothing happens when i press "timeline" button

**Comment by jafu888** [comment]
Testing out/Fixing Link this weekend. 
The protocol changed slightly to use it for test and we did not update link. 

It's interesting:
Our test run the LinkServer and query it from within the app for the layout then do string comparisons.  
So you can set the Transition 50% and verify everything moved. 
Long term we want to do more formal comparisons with tolerances on floats.   

But I am running out of time to fix link today.

**Comment by adrianwitaszak** [comment]
No worries. You doing grat job anyway. 
btw just tried Link with `sample18` and timeline works as expected.
