### ISSUE TITLE
[MotionLayout+Compose] Issue with Text

### ISSUE THREAD

**Issue by egorikftp** [androidx/constraintlayout#485]
Hey, I'm working with MotionLayout and Compose and found a strange bug with **Text**.

For example, we have **Text()** composable to display "Current time". If we press "Change text" button, I concatenate strings and set "Current time: 1641989350106" into **Text()**.
Then, press "Run" button and you will see the animation appear with default text.

After that, I'm not able to change text anymore.

Please see attached video:

https://user-images.githubusercontent.com/16294951/149136804-b01adce4-200d-414a-b0eb-055845d784a8.mp4

Also, I have created a 100% reproducibility sample: 
https://github.com/egorikftp/ComposeTextBug/tree/master

ConstraintLayout Compose: 1.0.0-rc02

_Expected result:_

- The animation starts with the actual text
- User able to change text value

**Comment by jafu888** [comment]
The text is change the layout is not.
So you widget is clipping the text.

**Comment by egorikftp** [comment]
Well, I use `wrap` tag and assume that it will be like "wrap content". 
Correct me if I'm wrong.

```
width: 'wrap',
height: 'wrap'
```

I mean that if I change the text value in the Text() composable, I expect that the bounds of Text() also change. Now I see that during animation Text() clipping.

**Comment by egorikftp** [comment]
Also, I found another issue with Text().
In case we have swipeable functionality in MotionLayout and set different textSize for start and end state, the Text() updates _only_ after user interaction

https://github.com/egorikftp/ComposeTextBug/tree/swipe_issue

https://user-images.githubusercontent.com/16294951/149301652-94867325-8ce9-4acb-93ff-2f350e935275.mp4

**Comment by jafu888** [comment]
It is a bug. 
I was explaining the bug.

The wrap sizes for the animation get stuck at the initial size.
They do not update when the text is changed.
You had written it as: "After that, I'm not able to change text anymore."
In general wrap is not calculated on each frame. The animation would be too slow.
Wrap should be recalculated each time a widget changes.  (In views it is requestlayout)
Compose is a bit more complex than that.
