### ISSUE TITLE
Update changelogs for releases

### ISSUE THREAD

**Issue by vbuberen** [androidx/constraintlayout#493]
Looks like latest releases don't have list of changes mentioned. 
Would be good to have proper changelogs as it was before.

**Comment by jafu888** [comment]
https://github.com/androidx/constraintlayout/releases/tag/2.1.3

**Comment by vbuberen** [comment]
Thanks a lot

**Comment by jafu888** [comment]
Thanks for pointing it out to me. 

A large part of the work we did was not part of the content of the release. 
Validation that we have all the features of XML ConstraintLayout. 
Hiding API internal API etc.
