### ISSUE TITLE
2.0.0-beta6 and higher - autoTransition="animateToStart"  not work

### ISSUE THREAD

**Issue by ZhuSniffsTheRose** [androidx/constraintlayout#50]
when I click 'trigger'  and MotionLayout finish `start` to `end`,  expect it can back to `start`. unfortunately, animateToStar not working. 

I find some differ in MotionLayout. there is the condition that `this.mCurrentTransition == transition` in  MotionScene#autoTransition(...),   can u explain what's the meaning of it?

**Comment by ZhuSniffsTheRose** [comment]
I suggest that remove the condition in MotionScene.java:
```
if (transition.mAutoTransition == Transition.AUTO_NONE) {
    continue;
}
```

**Comment by jafu888** [comment]
That was add to prevent what you are trying to do because others saw it is a bug. We messed up on making the API ambiguous. We will add another flag to support your use case.
