### ISSUE TITLE
[since 2.1.0] NoSuchMethodError:   No virtual method getViewWidget

### ISSUE THREAD

**Issue by JustAllIn** [androidx/constraintlayout#500]
my app works depend on an third-party library

the library is **NOT** developed with AndroidX 

so I have this config in my `gradle.properties`

`android.useAndroidX=true`
`android.enableJetifier=true`

both my app and the library use `ConstraintLayout` , so I also have an dependency in `app/build.gradle`

`implementation "androidx.constraintlayout:constraintlayout:2.0.4"`

--- 

here is the problem  ↓  
I've tried many times and found that : 
when I use version `2.0.4 or lower` , everything works well
but when I use version `2.1.0 or higher` , the crash happens 

>java.lang.NoSuchMethodError: No virtual method getViewWidget(Landroid/view/View;)Landroidx/constraintlayout/solver/widgets/ConstraintWidget; in class Landroidx/constraintlayout/widget/ConstraintLayout; or its super classes (declaration of 'androidx.constraintlayout.widget.ConstraintLayout' appears in /data/app/~~v1a0Bi1CmvvfZ2ykmN94CA==/com.example.sdkdemo-9coDvBRn03a-3DEvbJE6Dg==/base.apk)
        at com.douyu.livesdk.floatUI.planB.FloatPlayerView.a(SourceFile:636)
        at com.douyu.livesdk.floatUI.planB.FloatPlayerView.a(SourceFile:161)
        at com.douyu.livesdk.floatUI.items.RoomItemHolder$1.onClick(SourceFile:76)

I find out the soure code in library and the log located on this line 

`rootView.getViewWidget(playerView).setDimensionRatio("W,16:9")`

`rootView` is instance of ConstraitLayout

---
I have no idea except to rollback the version of ConstraintLayout to 2.0.4 

I read  up the change log on Wiki but find nothing about it 
 
so I think this might be a **BUG**

or if there is some other solutions for my issue ?

**Comment by jafu888** [comment]
In general if you depend on a library that uses another library you must all use the same version.
You cannot have two versions of ConstraingLayout (or any library for that matter) in one application.
