### ISSUE TITLE
I use three child view as a vertical chain in a fixed height ConstraintLayout as a container, but the top and bottom view ha s been squeezed 

### ISSUE THREAD

**Issue by aLLLiyyy** [androidx/constraintlayout#558]
I use three child view as a vertical chain in a fixed height ConstraintLayout as a container, but the top and bottom view has been squeezed out of the container's  boundary,because the center view of the vertical chain has a large fixed size ,is it a bug or something?   I wanna take a glance at this measure logic in source code , could you paste the relative code to me, thank you,

**Comment by jafu888** [comment]
The logic (which can be found in [core](https://github.com/androidx/constraintlayout/tree/main/constraintlayout/core/src))
The code is very complex. 

But a rough description is that patterns of Constraints result in a series of equations with error terms. A solver tries to minimize the errors. 
Before the solver is run an optimizer tries to pre solve equations with known direct solutions.  

So if you specify a series of constraint with no solution  you wont get the one you want.
There are some things you might change to shift the priority in cases such as the one you describe. 
For example you might specify 0dp but with a min or max height.

**Comment by aLLLiyyy** [comment]
I am very appreciated for your reply.but still confused, and i need to dive myself into reading the complicated measure logic. hope i can gain something,thankyou

**Comment by jafu888** [comment]
This is working as intended.
At its core fixed height means it cannot change.
Going outsides the containers boundary is not a bug.
If you want flexible resizing of a child view they need to be 0dp
