### ISSUE TITLE
animation need to more flexible

### ISSUE THREAD

**Issue by devzhan** [androidx/constraintlayout#581]
When motionlayout sets the interpolator through the Seibel curve, it will calculate the interpolator through easing. This calculation method is different from the implementation method of pathinterpolator of attribute animation. We found a slight jam when calculating interpolator on some curves. It is suggested to add the implementation method of motioninterpolator attribute to meet the definition of interpolator more flexibly.
I have found that there are differences in animation through modifying the source code

**Comment by devzhan** [comment]
The curve is cubic (0.22f, 0.12f, 0.25F, 0.99f), but there is a Caton effect through motionlayout, and it is more smooth to change the same curve into attribute animation. The method of obtaining interpolator by modifying the interior of motionscene is pathinterpolator. The effect of interpolator is the same as that of attribute animation

**Comment by jafu888** [comment]
"The curve is cubic (0.22f, 0.12f, 0.25F, 0.99f), but there is a Caton effect through motionlayout, "
I do not know what "Caton effect is".

" it is more smooth to change the same curve into attribute animation."
What do you mean by "attribute animation"?

" The method of obtaining interpolator by modifying the interior of motionscene is pathinterpolator. "
We do not have a method named "pathinterpolator" so I am not sure what you are talking about.

"The effect of interpolator is the same as that of attribute animation"
What "interpolator" what  "attribute animation"


So you are not getting this?
https://www.cssportal.com/css-cubic-bezier-generator/#0.22,0.12,0.25,0.99

![image](https://user-images.githubusercontent.com/15019413/168339775-39fde1e7-dc58-4c57-bf0c-e08943794af2.png)

I am assuming you are typing something like:

```xml
<Transition
    motion:constraintSetEnd="@id/set_second"
    motion:constraintSetStart="@id/set_first"
    motion:motionInterpolator="cubic(.22, 0.12, 0.25, 0.99)"
    motion:duration="300"/>

    ```

Could create a simple example or source code/xml?
Or could you poast a GIF's of what you want?.
Or point to file/line numbers in our code?
