### ISSUE TITLE
MotionLayout Custom custom property bug

### ISSUE THREAD

**Issue by jafu888** [androidx/constraintlayout#627]
The custom property bug is due to different lifecycle it seems
The calls are captured before the layout
  

example -- proper interpolation of 
1/ custom colors (top/bottom colors of the gradient) 
2/ some float value, used to compute final color and thus distinguish between "current item" vs others (the current item has value of 1, rest have nothing so 
0). So no need to have a notion of progress or who's the main item, just have the option to pass the motionproperties and use them.

https://user-images.githubusercontent.com/15019413/173118367-db978754-77cd-4069-bafd-9668a98a044a.mov

**Comment by camaelon** [comment]
Current tip of tree showing the broken behavior:

https://user-images.githubusercontent.com/23424811/173119478-9ba68043-c9b2-4b7c-b757-d81f45dfe9fb.mov

**Comment by oscar-ad** [comment]
I think it might work by just calculating the custom properties with the `motionProgress` value at recomposition. I think the custom properties should work more like a stateless class that gets updated during composition with the progress value and transition to interpolate.
