### ISSUE TITLE
How do I implement this layout using constraintlayout

### ISSUE THREAD

**Issue by c1105590204** [androidx/constraintlayout#644]
When the content is small, the RV height wrap to the content, and when the content is large, the RV height increases, but does not exceed the scope of the Constraint Layout, and there is some padding around the constraint Layout.
![5F5YAH1}BVC6D04$X)GYQ~3](https://user-images.githubusercontent.com/13132540/177475333-c9d202ff-9c9b-42ab-90ef-91b6b5b3ae68.png)
thanks!

**Comment by jafu888** [comment]
Unclear what you are trying to achieve but.
That should be
 height=0dp 
 layout_constraintWidth_default="wrap" 
 bottom_toBottom=parent
 top_toTop=parent
 layout_constraintHorizontal_bias=0
 verticalBias = 0

**Comment by c1105590204** [comment]
> Unclear what you are trying to achieve but. That should be height=0dp layout_constraintWidth_default="wrap" bottom_toBottom=parent top_toTop=parent layout_constraintHorizontal_bias=0 verticalBias = 0

thanks!  layout_constraintWidth_default is the attribute I want,but I should use layout_constraintHeight_default instead.
