### ISSUE TITLE
TextView does not resize during transition with MotionLayout 

### ISSUE THREAD

**Issue by CamiloDelReal** [androidx/constraintlayout#7]
If a TextVIew is being resizing during a transition, and the layout_width or layout_height was set to wrap_content, then the widget is not resized well, most of the time the widget flick showing only a part of the component
Tested with constraintlayout v2.0.1

**Comment by pratikbutani** [comment]
Can you please put a video or gif to make me understand this thing more clear?

**Comment by jafu888** [comment]
For performance reasons  MotionLayout does not honor layout request during animation.
It is seldom needed and has a large performance penalty. This is because many types of views when in doubt call requestLayout just to be on the safe side. 
This can result in the effect you describe. Could you test by  adding the below to you Transition?
```xml
    <Transition     motion:layoutDuringTransition="honorRequest" \>

**Comment by CamiloDelReal** [comment]
Oops I forgot to reply the first message. I tried this morning again using wrap_content. the problem persist in 2.0.4. I tried too with honorRequest, this time the view rect wasn't correctly painted at 100%, the text content blinks. I attached gif's and the sample project for it. First picture is the transition without honorRequest, the second one is using honorRequest
[testing-motion.zip](https://github.com/androidx/constraintlayout/files/5488641/testing-motion.zip)

![motionlayout-textview-bad-layout](https://user-images.githubusercontent.com/40240381/98129266-3a402f00-1eb9-11eb-9f64-8f6e65007745.gif)
![motionlayout-textview-bad-layout-requestHonor](https://user-images.githubusercontent.com/40240381/98129430-678cdd00-1eb9-11eb-9b64-6b5a4bfb7e34.gif)

**Comment by jafu888** [comment]
This will happen as long as the text is wrap content. 
As the bounds change the text grows at a slightly different quantized pattern.
Every so often it wraps. 
The quick and dirty workaround it add white space around the text (It wraps the white space).
Another workaround is fixing the size of the text filed. 
Long term we will have to build a variant of text view that is padded.

**Comment by CamiloDelReal** [comment]
I currently use fixed sizes, but I don't think fixes sizes could resolve it always in every case. 
But well, I think it can works for now :)

**Comment by jafu888** [comment]
We implemented MotionLabel to work around this.
