### ISSUE TITLE
[Compose - MotionLayout] - `fontColor` and `fontSize` custom properties are ignored in latest version 1.0.1

### ISSUE THREAD

**Issue by christos-peppas** [androidx/constraintlayout#706]
Font colour or size does not change  during the motionlayout transition in latest `compose:1.0.1`

Checkout the following sample app 
https://github.com/philipplackner/MotionLayoutCompose

Works as expected when using  `implementation "androidx.constraintlayout:constraintlayout-compose:1.0.0"`
Does not work: when using  `implementation "androidx.constraintlayout:constraintlayout-compose:1.0.1"`

**Comment by oscar-ad** [comment]
The next alpha release for 1.1.0 will contain a fix for this.

**Comment by jorgedotcom** [comment]
When will this release happen?

**Comment by oscar-ad** [comment]
We are aiming for early next week.

**Comment by oscar-ad** [comment]
You can now try 1.1.0-alpha04
Let us know if it solves the issue.
