### ISSUE TITLE
MotionLayout with drawer content

### ISSUE THREAD

**Issue by YusufbekIbragimov** [androidx/constraintlayout#743]
When I use motion layout in scaffold content, I can't open drawer content with scrolling. If I try to open drawer content, the motion layout will be worked. I know it is working well in XML but I can't find a solution to this problem.

This is my motion scene: https://gist.github.com/YusufbekIbragimov/aca18bd871468fa0372eb44346a7c6c0
This is my motion file: https://gist.github.com/YusufbekIbragimov/750a766eb3629b2b3b583d6fc58488ed
This is mu my main screen file: https://gist.github.com/YusufbekIbragimov/9030b17cc5ccc98aae5a2bd7cda61099

**Comment by jafu888** [comment]
MotionLayout  OnSwipe in Compose does not support nested scrolling.

**Comment by YusufbekIbragimov** [comment]
Can you give me advice about how to create my screen?
And when will this feature be added in MotionLayout or is no plan for it?

**Comment by jafu888** [comment]
https://github.com/androidx/constraintlayout/wiki/MotionLayout-based-Collapsing-toolbar

**Comment by YusufbekIbragimov** [comment]
Vertically scrollable component was measured with an infinity maximum height constraints, which is disallowed. One of the common reasons is nesting layouts like LazyColumn and Column(Modifier.verticalScroll()). If you want to add a header before the list of items please add a header as a separate item() before the main items() inside the LazyColumn scope. There are could be other reasons for this to happen: your ComposeView was added into a LinearLayout with some weight, you applied Modifier.wrapContentSize(unbounded = true) or wrote a custom layout. Please try to remove the source of infinite constraints in the hierarchy above the scrolling container.

** I can't find a solution to this bug. **

**Comment by jafu888** [comment]
We have no plans to support "nested scroll screen" in our current 1.1.0 development cycle.
Consider not using onswipe and implement your own [swipe](https://developer.android.com/jetpack/compose/gestures#swiping)

**Comment by YusufbekIbragimov** [comment]
Okay, thanks. I get enough information
