### ISSUE TITLE
Compose motion layout how Header will work?

### ISSUE THREAD

**Issue by Debdutta-Panda** [androidx/constraintlayout#772]
I have gone through the motion layout wiki, https://github.com/androidx/constraintlayout/wiki/Compose-MotionLayout-JSON-Syntax#header , but could not found `Header` usage sample, concept, etc. Are there any resource from where I can find its usage? Thanks in advance

**Comment by jafu888** [comment]
It is used with Link. https://github.com/androidx/constraintlayout/wiki/How-to-use-Link
Link is an experimental mechanism to remote access and control MotionLayout Compose
It will be used in the future for debug flags, optimization flags

**Comment by Debdutta-Panda** [comment]
Great, thanks a lot.
