### ISSUE TITLE
Compose motion layout keyCycle waveShape, customWave working mechanism, are there any related doc?

### ISSUE THREAD

**Issue by Debdutta-Panda** [androidx/constraintlayout#773]
I was going through the source code of compose motion layout. I found `waveShape`, `customWave` features. But could not find any related doc. So, are there any related doc? Thanks in advance.

**Comment by jafu888** [comment]
This has not been tested yet in Compose. (Functionality is coming from XML)

In general you can set:
- "sin" 
- "square"  
- "triangle"  
- "sawtooth"  
- "reverseSawtooth" 
- "cos" 
- "bounce" 
- "custom(0,0.3,0,-0.1,1,-0.5,0,0,0,0)"
 
 They all represent repeating patterns see  https://youtu.be/qWmU6emSQ5k?t=73
 Custom allows you to create a pattern  by setting the heights of evenly spaces points -1 to 1
 They will be tested as we make progress to release.

**Comment by Debdutta-Panda** [comment]
I also was thinking like this, as I tested without any result. Thanks for the confirmation.
