### ISSUE TITLE
Attribute "android:alpha" has already been defined

### ISSUE THREAD

**Issue by xuyisheng** [androidx/constraintlayout#81]
compile with 'androidx.constraintlayout:constraintlayout:2.0.4'

runs error:

Attribute "android:alpha" has already been defined
Attribute "android:translationX" has already been defined
Attribute "android:translationY" has already been defined
Attribute "android:translationZ" has already been defined

**Comment by kaeawc** [comment]
@xuyisheng What version of AGP are you using? Is it older than `3.0.1`?

**Comment by kaeawc** [comment]
@xuyisheng or are you trying to pin the versions for both `constraintlayout` and `solver`? You cannot use the old solver version with the newer `constraintlayout` module.

**Comment by zxw1962** [comment]
@kaeawc we use AGP 3.2.1 & gradle version 4.6, got the same errors. 
Seems the root cause is the "PropertySet" defined in attrs.xml with <attr name="android:alpha" format="float" />
(I guess the format="float" should be removed here?). 
What do you say? Thanks in advance.

**Comment by xuyisheng** [comment]
> @xuyisheng What version of AGP are you using? Is it older than `3.0.1`?

My AGP is 3.2.0，and constraintlayout version of 2.0.4, I have checked version of constraintlayout and solver, it's all right

**Comment by xuyisheng** [comment]
Are you making progress ？

**Comment by zxw1962** [comment]
> Are you making progress ？
![image](https://user-images.githubusercontent.com/1560302/106227908-26406b00-6225-11eb-9511-677ef9efd8bb.png)
we use the above version to workaround this error.
