### ISSUE TITLE
In Android8.1 (27), the round setting is too large, and the ImageFilterView cannot be displayed

### ISSUE THREAD

**Issue by john990** [androidx/constraintlayout#814]
I want to create an ImageView with a circular background, implemented using ImageFilterView, which is displayed normally on 27+ systems, but cannot be displayed in Android 8.1.

Constraintlayout version:

```
androidx.constraintlayout:constraintlayout:2.1.4
```

Layout xml code：

```xml
<androidx.constraintlayout.utils.widget.ImageFilterView
        android:id="@+id/gallery_button"
        android:layout_width="48dp"
        android:layout_height="48dp"
        android:layout_marginStart="20dp"
        android:clickable="true"
        android:background="@color/black_30"
        android:foreground="?attr/selectableItemBackground"
        android:src="@drawable/ic_round_photo_library_24"
        app:round="1000dp"
        android:padding="13dp"
        app:tint="@color/white"/>
```

Android10 screenshot(work fine):
![Snipaste_2023-05-12_10-43-47](https://github.com/androidx/constraintlayout/assets/5292685/0f4a0220-c713-437c-af2b-7bbf54048225)

Android8.1 screenshot:
![Snipaste_2023-05-12_10-45-07](https://github.com/androidx/constraintlayout/assets/5292685/2c844a18-ba13-4c37-98b8-566931164c0b)

**Comment by jafu888** [comment]
`app:round="1000dp"`
might be a problem
I would recommend
`app:roundPercent="1"`

In general it should work back to Android 5.x  (Lollipop)
Try to first put a simple  white view in its place.
To make sure some other change is not obscuring the widget.
For example it could be the way the camera is being implemented .

**Comment by john990** [comment]
> `app:round="1000dp"` might be a problem I would recommend `app:roundPercent="1"`
> 
> In general it should work back to Android 5.x (Lollipop) Try to first put a simple white view in its place. To make sure some other change is not obscuring the widget. For example it could be the way the camera is being implemented .

``` app:roundPercent="1" ``` works great! thank you so much!
